apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
spec:
  selector:
    matchLabels:
      app: jenkins
  replicas: 1
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      serviceAccountName: jenkins
      containers:
        - name: jenkins
          image: ghcr.io/mercurial963/jenkins:latest
          imagePullPolicy: Always
          env:
            - name: JAVA_OPTS
              value: -Djenkins.install.runSetupWizard=false
          ports:
            - name: http-port
              containerPort: 8080
            - name: jnlp-port
              containerPort: 50000
          volumeMounts:
            # - mountPath: /var/jenkins_home
            #   name: jenkins-pv-storage
            - name: jenkins-home # use "jenkins-home"(refer from name and emptyDir) if not use persistent volume
              mountPath: /var/jenkins_home
      volumes: 
        # - name: jenkins-pv-storage
        #   persistentVolumeClaim:
        #     claimName: jenkins-pv-claim
        - name: jenkins-home
          emptyDir: {}
      imagePullSecrets:
      - name: registry-jenkins